#!/usr/bin/env bash
# a script that installs update the ubuntu, install nginx, make sure its listening to port 80, and also add uncomplicated firewall

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
