#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

balancer="\
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend webservers

backend webservers
	balance roundrobin
	server 526725-web-01 18.234.107.80 check
	server 526725-web-02 18.207.142.76 check
"

#update packages
sudo apt-get -y update
sudo apt-get upgrade -y

#Add HAProxy PPA
sudo apt-get install software-properties-common -y
sudo apt-get-repository ppa:vbernat/haproxy-2.5 -y
sudo apt-get update -y

#Install HAProxy
sudo apt-get install haproxy -y
cp -a  /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
